### ISSUE TITLE
unicode error in transcoder.py

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/sanskrit-transcoding#1]
@funderburkjim,
When I ran your code as a module in one python code which I wrote,
it gave the following error.
Some unicode error at line 250 of the code.
![screenshot from 2015-08-29 22 08 42](https://cloud.githubusercontent.com/assets/5755132/9563228/dac42124-4e9a-11e5-94fa-72f648dbabfa.png)

**Comment by funderburkjim** [comment]
I think this is related to the print statement, not to transcoder logic.
In Python 2, when you say
```
print x
```
where 'x' has the value of a unicode string  (i.e., it is not just ascii), then you get that
UnicodeDecodeError message.
But, if you use
```
print x.encode('utf-8')
```
then the error goes away.
So, in your case, I would try
```
x = devanagaridisplay("aMSakatas")
print x.encode('utf-8')

OR likely this would work (without the temporary variable 'x')
print devanagaridisplay("aMSakatas").encode('utf-8')
```

**Comment by drdhaval2785** [comment]
thanks for the pointer.

It worked, but not encode - it is decode that worked.

e.g. `output = output.decode('utf-8')` before returning output in function devanagaridisplay.

**Comment by drdhaval2785** [comment]
It seems that the transcoder presumes that the input would be in utf-8 and when it got 'str', it failed. I converted the string to utf-8 before passing to transcoder and then it worked.

**Comment by funderburkjim** [comment]
Your comments seem slightly off target from my experience.  
Could you post your entire code example somewhere?

**Comment by funderburkjim** [comment]
@drdhaval2785   I'd like to see the code example, because I didn't understand why the 'decode' would be needed.
